services:
  - type: web
    name: darkrite
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      apt-get update -y
      apt-get install -y ghostscript fonts-dejavu-core

    startCommand: gunicorn app:app
